-- MySQL Script generated by MySQL Workbench
-- Thu Dec  6 17:28:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_tienda_segunda_mano
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_tienda_segunda_mano` ;

-- -----------------------------------------------------
-- Schema db_tienda_segunda_mano
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tienda_segunda_mano` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `db_tienda_segunda_mano` ;

-- -----------------------------------------------------
-- Table `db_tienda_segunda_mano`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tienda_segunda_mano`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `db_tienda_segunda_mano`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `pass` VARCHAR(255) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNac` DATE NULL,
  `fechaCreacion` DATETIME NULL,
  `fechaModificacion` DATETIME NULL,
  `estado` INT NULL,
  `perfil` INT NULL,
  `avatar` LONGBLOB NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`idUsuario` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_tienda_segunda_mano`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tienda_segunda_mano`.`categoria` ;

CREATE TABLE IF NOT EXISTS `db_tienda_segunda_mano`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `id_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tienda_segunda_mano`.`subcategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tienda_segunda_mano`.`subcategoria` ;

CREATE TABLE IF NOT EXISTS `db_tienda_segunda_mano`.`subcategoria` (
  `idSubcategoria` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idSubcategoria`),
  INDEX `fk_subcategoria_categoria2_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categoria2`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `db_tienda_segunda_mano`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `db_tienda_segunda_mano`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tienda_segunda_mano`.`productos` ;

CREATE TABLE IF NOT EXISTS `db_tienda_segunda_mano`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` DECIMAL(5,2) NULL,
  `fechaCreacion` DATETIME NULL,
  `idVendedor` INT NOT NULL,
  `idComprador` INT NULL,
  `idCategoria` INT NOT NULL,
  `idSubcategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_productos_usuarios_idx` (`idVendedor` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`idProducto` ASC) VISIBLE,
  INDEX `fk_productos_usuarios1_idx` (`idComprador` ASC) VISIBLE,
  INDEX `fk_productos_categoria1_idx` (`idCategoria` ASC) VISIBLE,
  INDEX `fk_productos_subcategoria1_idx` (`idSubcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_productos_vendedor`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `db_tienda_segunda_mano`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_comprador`
    FOREIGN KEY (`idComprador`)
    REFERENCES `db_tienda_segunda_mano`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `db_tienda_segunda_mano`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_subcategoria1`
    FOREIGN KEY (`idSubcategoria`)
    REFERENCES `db_tienda_segunda_mano`.`subcategoria` (`idSubcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tienda_segunda_mano`.`fotosProductos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tienda_segunda_mano`.`fotosProductos` ;

CREATE TABLE IF NOT EXISTS `db_tienda_segunda_mano`.`fotosProductos` (
  `idFotoProducto` INT NOT NULL AUTO_INCREMENT,
  `imagen` BLOB NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idFotoProducto`),
  INDEX `fk_fotosProductos_productos1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_fotosProductos_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `db_tienda_segunda_mano`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tienda_segunda_mano`.`historicoUsuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tienda_segunda_mano`.`historicoUsuarios` ;

CREATE TABLE IF NOT EXISTS `db_tienda_segunda_mano`.`historicoUsuarios` (
  `idHistorico` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `passAntigua` VARCHAR(255) NULL,
  INDEX `fk_historicoUsuarios_usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  PRIMARY KEY (`idHistorico`),
  UNIQUE INDEX `id_UNIQUE` (`idHistorico` ASC) VISIBLE,
  CONSTRAINT `fk_historicoUsuarios_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `db_tienda_segunda_mano`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tienda_segunda_mano`.`opiniones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_tienda_segunda_mano`.`opiniones` ;

CREATE TABLE IF NOT EXISTS `db_tienda_segunda_mano`.`opiniones` (
  `idOpiniones` INT NOT NULL AUTO_INCREMENT,
  `valoracion` INT NULL,
  `mensaje` VARCHAR(255) NULL,
  `fechaOpinion` DATETIME NULL,
  `idProducto` INT NOT NULL,
  `idUsuarioOpinion` INT NOT NULL,
  PRIMARY KEY (`idOpiniones`),
  INDEX `fk_opiniones_usuarios1_idx` (`idUsuarioOpinion` ASC) VISIBLE,
  INDEX `fk_valoraciones_productos2_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_valoraciones_productos2`
    FOREIGN KEY (`idProducto`)
    REFERENCES `db_tienda_segunda_mano`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opiniones_usuarios1`
    FOREIGN KEY (`idUsuarioOpinion`)
    REFERENCES `db_tienda_segunda_mano`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_tienda_segunda_mano`.`usuarios` 
(`username`, `email`, `pass`, `nombre`, `apellido1`, `apellido2`, `direccion`, `fechaNac`, `fechaCreacion`, `fechaModificacion`, `estado`, `perfil`, `avatar`) 
VALUES 
('usuario', 'usuario@gmail.com', '$2y$10$OFDnVH9y.oHgJOYy1K8JNu.n78UDRivOb0uX463YtLTdKwWAWJkfG', 'Usuario', 'User', 'User', 'Casa usuario', '2000-01-01', NOW(), NOW(), 0, 0, NULL),
('admin', 'admin@iesgalileo.es', '$2y$10$OFDnVH9y.oHgJOYy1K8JNu.n78UDRivOb0uX463YtLTdKwWAWJkfG', 'Administrador', 'Admin', 'Admin', 'Casa administrador', '2000-01-01', NOW(), NOW(), 0, 1, NULL);
